version: '3'

services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/app
    ports:
      - "8000:8000"

  prod:
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - "80:80"