FROM python:3.9-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install -r requirements.txt

RUN mkdir -p /app/content/images
RUN mkdir -p /app/content/static

EXPOSE 8000

CMD ["pelican", "--listen", "--autoreload", "--bind", "0.0.0.0"]